# Generated by Django 6.0.3 on 2026-04-04 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='total_bal',
        ),
    ]
