# Generated by Django 6.0.3 on 2026-09-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
                ('app_name', models.CharField(default='Trading app', max_length=120)),
            ],
        ),
        migrations.RenameField(
            model_name='upgrade_plan',
            old_name='plans',
            new_name='plan',
        ),
    ]
