# Generated by Django 6.0.3 on 2026-04-10 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_dashboard_user_passwordid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordid',
            name='reset_id',
            field=models.CharField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
