# Generated by Django 6.0.3 on 2026-04-16 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_deposit_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mode_Of_Payment', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='deposit',
            name='mode_of_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.paymentmethod'),
        ),
    ]
