# Generated by Django 6.0.3 on 2026-04-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_paymentmethod_deposit_mode_of_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_coin', models.CharField(max_length=50)),
                ('wallet_address', models.CharField(max_length=100)),
                ('network', models.CharField(max_length=50)),
            ],
        ),
    ]
