# Generated by Django 6.0.3 on 2026-05-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_paymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='wallet_address',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
