# Generated by Django 6.0.3 on 2026-05-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_paymentmethod_wallet_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentDetails',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='Mode_Of_Payment',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='name_of_coin',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='network',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='wallet_address',
            field=models.CharField(max_length=100),
        ),
    ]
