# Generated by Django 6.0.3 on 2026-05-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_delete_paymentdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='wallet_address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
